export const NAVIGATION_DRAWER_ICON_WIDTH = 24;
export const NAVIGATION_DRAWER_TEXT_MARGIN = 16;
export const NAVIGATION_DRAWER_TEXT_WIDTH = 120;

export const NAVIGATION_DRAWER_RAIL_WIDTH = NAVIGATION_DRAWER_ICON_WIDTH + (NAVIGATION_DRAWER_TEXT_MARGIN * 2);
