name: 'Autotag'

on:
  push:
    branches:
      - main

jobs:
  autotag:
    name: Tag with ui-components/package.json version
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      actions: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: ui-components

      - name: Create tag
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ steps.package-version.outputs.current-version}}',
              sha: context.sha
            }).catch(err => {
              if (err.status !== 422) throw err;
              console.log('Tag for version "${{ steps.package-version.outputs.current-version}}" already exists. Skipping tag creation.');
            })
